// dsh-notes client 模块清单（唯一组装依据）
// 顺序 = 拼接顺序 = 标识符可见顺序（kernel → modals → panels，architecture-modular.md §4.2）
// modals 排在 panels 之前：modal 模块只依赖 kernel（禁横向引用由序位强制），whole.js 装配点经模块顶层标识符挂载
// 以 @shared/ 开头的条目解析到 src/shared/（两态物理共源块，§4.3 例外）：
//   共源文件按列 0 维护，client 态纳入时逐非空行加 4 空格基座缩进（单文件时代 apply 函数体层级；app 态列 0 原样纳入）
// 以 @i18n/ 开头的条目解析到 src/i18n/（notes-042-i18n-mech 双语字典，共源 + 基座缩进规则与 @shared/ 完全一致）
// 解析契约：模块路径独占一行、单引号包裹；注释中禁止出现单引号字符——
// host 沙箱侧 notes-src 与 scripts/concat-client.cjs 统一按单引号正则文本解析本文件。
module.exports = [
  'kernel/bootstrap.js',
  'kernel/bus.js',
  'kernel/state.js',
  '@i18n/zh.js',
  '@i18n/en.js',
  'kernel/i18n.js',
  'kernel/persist.js',
  'kernel/constants.js',
  'kernel/format.js',
  'kernel/icons.js',
  '@shared/editor-kernel.js',
  'kernel/perf.js',
  'kernel/css-loader.js',
  'kernel/drag.js',
  // triggers/mentions.js：0.4.5-E @ 引用笔记源（kernel 之后——依赖 bus/i18n/constants 序位在前；独立于 modals/panels 的宿主接线模块）
  'triggers/mentions.js',
  'modals/link.js',
  'modals/image.js',
  'modals/merge.js',
  'modals/newnote.js',
  'modals/history.js',
  'modals/trash.js',
  'modals/prune.js',
  'modals/archive.js',
  'modals/export.js',
  'modals/export-single.js',
  'modals/import.js',
  'modals/inject-preview.js',
  'modals/inject-manager.js',
  'modals/organize-instruct.js',
  'modals/suggest.js',
  'modals/memory-guide.js',
  'modals/dispatch.js',
  'modals/cheatsheet.js',
  'modals/settings.js',
  'popovers/help.js',
  'popovers/selbar.js',
  'popovers/folder-menu.js',
  'popovers/ctx-menu.js',
  'popovers/scope.js',
  'popovers/filter-pop.js',
  'popovers/sort-menu.js',
  'panels/entries/header-button.js',
  'panels/entries/fab.js',
  'panels/entries/injected-badge.js',
  'panels/panel/search.js',
  'panels/panel/wiki.js',
  'panels/panel/tree.js',
  'panels/panel/editor.js',
  'panels/panel/sidebar.js',
  'panels/panel/chrome.js',
  'panels/panel/keyboard.js',
  'panels/selection/capture.js',
  'panels/panel/index.js',
]
